### ISSUE TITLE
Enchantments cannot be stacked properly

### ISSUE THREAD

**Issue by Teaftc** [cloudnode-pro/EnchantBookPlus#15]
Two books of Sharpness 5 cannot be combined into Sharpness 6 but into Sharpness 4, and then Sharpness 4 can be normally combined into Sharpness 5, and so on.
In 1.21.1, you can consume experience normally according to the formula, but you cannot stack enchantments.
The following is a video of 1.20.6
Minecraft server type and version : Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
Plugin version : EnchantBookPlus 1.0.3
Warnings and errors related to this plugin in the console ：none
Steps to reproduce the issue
Video Link：https://drive.google.com/file/d/1J4urPxEITmIzbDbgHS4ZXeL8WwmE3T8l/view?usp=drive_link

**Comment by zefir-git** [comment]
Hi! I don't have access to the video. Could you please upload it here or make it public?

Please confirm that you have set in the config:
```yaml
# ...
    -   name: sharpness
        max-level: 6
        # ...
```
and have the `enchantbookplus.enchant.sharpness` permission

**Comment by Teaftc** [comment]
![image](https://github.com/user-attachments/assets/1679f78a-19a3-410b-816a-5e761800ccfa)
After testing, it turned out to be a configuration problem on my part. I'm very sorry.
Is there any way to change the text in the image to Arabic numerals?

**Comment by zefir-git** [comment]
Glad the problem was solved.
Enchantments over the level of 10 show like this in Minecraft (regardless of how the enchantment is obtained, e.g. through commands).

One solution is to enable the "HideEnchantments" NBT tag and then add custom lore. You have to be careful as if the enchants change, the lore will need to be updated.

I'm guessing that it might also be possible to add your own translations for "enchantment.level.15" as additional translations, perhaps using a resource pack.

**Comment by zefir-git** [comment]
In the default MC resource pack `/assets/minecraft/lang/en_us.json` there's:

```json
  "enchantment.level.1": "I",
  "enchantment.level.2": "II",
  "enchantment.level.3": "III",
  "enchantment.level.4": "IV",
  "enchantment.level.5": "V",
  "enchantment.level.6": "VI",
  "enchantment.level.7": "VII",
  "enchantment.level.8": "VIII",
  "enchantment.level.9": "IX",
  "enchantment.level.10": "X",
```

I would try adding like `"enchantment.level.15": "XV",` and then put the resource pack as a server resource pack
